name: Tests

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: "temurin"
      - run: npm ci
      - run: mvn verify
